Frontend register
upmeals/upmeals pull request #10
Opened 2021-12-08 19:41 UTC by VianneyDev

modal register avec lien entre connexion/inscription, ajout css sur le cta actif + tenté de virer l'outline de la modal global mais no time no more

2021-12-12 19:02 UTC, zKolait requested changes
J'ai essayé de bien détailler pour que tu comprennes bien la logique qui permet de faire le switch incription/connexion de façon clean

2021-12-12 19:02 UTC, zKolait commented on frontend/src/components/frontend/auth/login/LoginForm.js
> +            height: '75vh',
Cela vaux aussi pour register mais il faudrait que la hauteur soit fixe entre les deux

A voir si on fait ca en px pour qu'il y ait moins d'espace

Il faudra aussi changer ModalLogin du coup pour avoir une taille fixe !

500px me semble pas mal je te laisse tester

2021-12-12 19:02 UTC, zKolait commented on frontend/src/components/frontend/auth/register/RegisterForm.js
> -import { Grid, TextField, InputLabel, Button } from '@mui/material';
Il faut les memes changements que dans LoginForm

- Principalement les couleurs 
- Taille (vh -> px)
- Police

2021-12-13 14:25 UTC, VianneyDev commented on frontend/src/components/frontend/auth/login/LoginForm.js
>              color: '#212121',
j'le rajoute mais il est présent de mon côté de base dans le component <Button>

2021-12-13 14:59 UTC, merged