Front/affichage card
upmeals/upmeals pull request #12
Opened 2021-12-12 17:20 UTC by Thevaleentiin

init branch affichage card

2021-12-12 19:12 UTC, zKolait requested changes

2021-12-12 19:12 UTC, zKolait commented on frontend/src/components/frontend/dashboard/listing/MealCard.js
> +import { makeStyles } from '@material-ui/core/styles';
Ce n'est pas à jour je viens de te merge avec develop tu dois faire de ton côté maintenant :

npm i

et update tous les imports de la page

Tu peux t'inspirer des autres page ou voir la doc direct sur MUI.

Je m'occupe de la review quand c'est fait

2021-12-12 21:12 UTC, Thevaleentiin commented on frontend/src/components/frontend/dashboard/listing/MealCard.js
> +import { makeStyles } from '@material-ui/core/styles';
j'ai fais les changements et j'ai push normalement

2021-12-13 09:05 UTC, zKolait requested changes
Bon code gg juste des petits changement pour que ce soit perfect

2021-12-13 09:05 UTC, zKolait commented on frontend/src/components/frontend/dashboard/listing/MealCard.js
> +        <Card className={classes.root}>
components: {
        MuiButtonBase: {
            defaultProps: {
                disableRipple: true,
            },
        },
    },
    
    Tu peux rajouter ce code dans "config/themes/frontend.js"
    
    Après overrides pour désactiver le ripple peu importe ou tu clique sur la card.
    
    Il faudrait le faire + du coup ajouter un '&:hover' dans le jsx pour un petit effet quand on passe au dessus des boutons

2021-12-13 09:05 UTC, zKolait commented on frontend/src/components/frontend/dashboard/listing/MealCard.js
> +            />
Il faudrait juste voir pour fixer la taille à 220x220 poru l'image et ne pas arrondir les coins du bas

2021-12-13 09:05 UTC, zKolait commented on frontend/src/components/frontend/dashboard/listing/MealCard.js
> +                        <AccessTimeOutlinedIcon fontSize="small" className={classes.cardInfosIcon} /> 45 mn.
en fontSize 200 ou 300 à voir

2021-12-13 09:05 UTC, zKolait commented on frontend/src/components/frontend/dashboard/listing/MealCard.js
> +                        <EuroOutlinedIcon fontSize="small" className={classes.cardInfosIcon} /> 8,13/pers.
en fontSize 200 ou 300 à voir

2021-12-13 09:05 UTC, zKolait commented on frontend/src/components/frontend/dashboard/listing/MealCard.js
> +                <Typography className={classes.cardActionContainer} variant="body2" component="div">
en fontSize 200 ou 300 à voir

Ce serait cool que ca passe sur une ligne

2021-12-14 22:04 UTC, merged